[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc.release]
rustflags = "-C target-feature=+crt-static -C link-arg=/SUBSYSTEM:WINDOWS,6.01"

[source.crates-io]
replace-with = "rsproxy"

[source.rsproxy]
registry = "sparse+https://rsproxy.cn/index/"
